// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOhIsfrHYXJz_ffuP7wspOAy35PryuD0',
    appId: '1:695605179145:web:0131a14c4028ddd0c119d8',
    messagingSenderId: '695605179145',
    projectId: 'tuning-app-789ce',
    authDomain: 'tuning-app-789ce.firebaseapp.com',
    storageBucket: 'tuning-app-789ce.firebasestorage.app',
    measurementId: 'G-P3JRYNC411',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzOhIsfrHYXJz_ffuP7wspOAy35PryuD0',
    appId: '1:695605179145:android:0131a14c4028ddd0c119d8',
    messagingSenderId: '695605179145',
    projectId: 'tuning-app-789ce',
    storageBucket: 'tuning-app-789ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOhIsfrHYXJz_ffuP7wspOAy35PryuD0',
    appId: '1:695605179145:ios:0131a14c4028ddd0c119d8',
    messagingSenderId: '695605179145',
    projectId: 'tuning-app-789ce',
    storageBucket: 'tuning-app-789ce.firebasestorage.app',
    iosBundleId: 'com.example.tuning_mobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzOhIsfrHYXJz_ffuP7wspOAy35PryuD0',
    appId: '1:695605179145:ios:0131a14c4028ddd0c119d8',
    messagingSenderId: '695605179145',
    projectId: 'tuning-app-789ce',
    storageBucket: 'tuning-app-789ce.firebasestorage.app',
    iosBundleId: 'com.example.tuning_mobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzOhIsfrHYXJz_ffuP7wspOAy35PryuD0',
    appId: '1:695605179145:web:0131a14c4028ddd0c119d8',
    messagingSenderId: '695605179145',
    projectId: 'tuning-app-789ce',
    authDomain: 'tuning-app-789ce.firebaseapp.com',
    storageBucket: 'tuning-app-789ce.firebasestorage.app',
  );
}

